# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 100cdae3dfa26430bfba2ca0e89df5aab376077d90420df225814ef47a70bdb48050d3c1fa9c45b2515b14f8c41db646ffa4b42d02ac3f3913eb0ef258d6de65

test:
  secret_key_base: 408b81408ea6c0a36e77da961e909c808307fc03ad4ebbaeef409fc906fb50d70914aad23fdfbc5ea17fae4fc1dd77ae2e69eab34eb9e83ccd8557ef17e9d1f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
